# Install using ./envs/build-aurora.sh
name: mofa
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.*

  # Services used by the workflow
  - redis==5.*
  - mongodb
  - parallel  # Used to launch monitor

  # Tools to work with crystalline and molecular data
  - conda-forge::chargemol
  - conda-forge::raspa2
  - openbabel

  - pip
  - pip:
    - git+https://github.com/exalearn/colmena.git  # Fixes for streaming not yet on PyPI
    # Install requirements from https://pytorch.org/docs/stable/notes/get_start_xpu.html
    - --extra-index-url https://download.pytorch.org/whl/test/xpu
    - torch==2.5.0+xpu
    - numpy<2  # torch 2.1 is built with numpy 1
    - -e ..[test]
