# Install CUDA from Anaconda
#
# Old intstructions:
#   module use /soft/modulefiles; module load conda
#   module load cudatoolkit-standalone/11.8.0
#   pip install torch==2.3.1 --index-url https://download.pytorch.org/whl/cu118
name: mofa
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python==3.10.*
  - openssl>3

  # Tools to work with crystalline and molecular data
  - openbabel
  - conda-forge::chargemol
  - conda-forge::raspa2

  # Services used by the workflow
  - redis-server
  - mongodb

  - pip
  - pip:
    - torch==2.1.0
    - numpy<2
    - tqdm
    - -e ..[test]
